monkeytype/cli.py
This turned out to be an easier PR than I expected. run_handler/run_path already use sys.argv directly; I just added a catchall argument to the argparser so it doesn't complain about additional tokens.
Doesn't look like there are tests for this in test_cli.py, but let me know if I should create a new one.
=> Support passing arguments to scripts (fixes #18)

.gitignore, CHANGES.rst, monkeytype/stubs.py, tests/test_stubs.py
Per #22, monkeytype generates invalid type signatures for NewType types because they are valid mypy annotations but `new_type()` gets inspected as a function at runtime. This PR special-cases support for objects with `__supertype__` to return their `__name__` instead of their repr, based on https://github.com/python/cpython/blob/v3.6.3/Lib/typing.py#L2227
Since a comment says `render_annotation` was derived from `inspect.formatannotation`, I'll point out that this PR causes render_annotation to disagree with inspect.formatannotation. I think this is okay in theory since render_annotation is used for mypy types while formatannotation is used for runtime inspection, but I'd appreciate a second opinion. For what it's worth, this patch allowed me to use monkeytype against my NewType-using …
=> Generate annotations for NewType types (fixes #22)

CHANGES.rst, monkeytype/config.py, tests/test_config.py
Just to reduce noise in the call trace store.
=> Exclude frozen importlib functions in default code filter.

CHANGES.rst, doc/configuration.rst, monkeytype/cli.py, monkeytype/config.py, tests/test_cli.py
Addressing #28, this PR adds the `cli_context()` method to Config so the CLI can use it as a context manager when running its command.
The command name is passed so implementations can, e.g., not run `django.setup()` with `monkeytype run manage.py` (as that would be redundant) but still run it for `stub`/`apply`.
=> Add Config.cli_context() as a hook for custom CLI initialization and cleanup logic.

monkeytype/config.py, tests/test_config.py
We need to fully resolve the filename when deciding to filter code because of possible discrepancies that might arise with symlinks (e.g. `/lib64` is symlinked to `/lib` - see #33).
Added a cache around the default filter as well since its essentially pure and adding symlink resolution created an incredibly large performance overhead. Fortunately, with the cache in place, this tool performs even faster than without the patch.
=> Improve the default code filter's correctness and performance.

README.rst
I tried to make the example more easy to follow by rearranging the sequence that information is presented. 
First, let users know what the two files contain. Then, start to work on the annotation part.
=> EHN: modify the example in README

Pipfile, Pipfile.lock, monkeytype/stubs.py, monkeytype/tracing.py, monkeytype/util.py, tests/test_stubs.py, tests/test_tracing.py, tests/test_util.py, tests/util.py
Howdy, I think this is what is needed for #9. It passes `pytest`, `flake`, and `mypy`. I'm not sure if I completely mangled the `Pipfile.lock` file though.
=> Add support for django.utils.functional.cached_property

doc/tracing.rst, monkeytype/cli.py, monkeytype/tracing.py
One small feature I would greatly appreciate so I don't have to write my own wrapper scripts: to be able to directly run modules directly just like (`python -m ...`).
I typically heavily lean on entry points scripts and the like when deploying python code, making `runpy.run_script` unpractical.
Feel free to bike shed, or decide you want a different verb, etc, but I'd greatly appreciate it if we can teach MonkeyType how to do this natively.
=> Add support to directly run a module

monkeytype/cli.py, tests/test_cli.py
This pull request implements the enhancement suggested in issues #7 
It supports `--sample-count` argument for both `stub` and `apply` two subparsers. Currently, it prints "Annotation for module.func based on N call trace(s)." to `stderr` line by line for each method. 
Some points that I am not sure
- `--sample-count` argument is checked at the `get_stub` function. Or it should be checked at `apply_stub_handler` and `print_stub_handler` separately?
-  The two functions, `display_sample_count` and `count_sample` seems to be able to merge into one function. I wrote it separately to test it separately. Should I merge them? 
Some other thoughts 
- add sort by frequency support?
Please let me know if there is anything I miss or any naming issue. I appreciate your review.
=> Support sample count

CHANGES.rst, monkeytype/cli.py, tests/test_cli.py
Catch retype failures and print the error so the user has a better
idea of what went wrong.
Fixes #49.
=> Display retype errors

monkeytype/cli.py, monkeytype/stubs.py, tests/test_cli.py, tests/test_stubs.py
This PR implements the enhancement suggested in issue #15 
The `update_signature_args` part is a bit complicated, and I am not sure whether I am doing it right. 
I tested whether a `typ` is `None` or `NoneType`. If so, I assign it as `inspect.Parameter.empty`. I think is related to issue #5 when it regarding parameters. Not sure this is the correct way to do.
I also added one line to  `apply_stub_handler` because I did not add option for `apply_parser` subparser. I need to manually make it `False` and make `get_stub` function aware of the parameter when it is called by `apply_stub_handler`.
```python
def apply_stub_handler(args: argparse.Namespace, stdout: IO, stderr: IO) -> None:
args.ignore_existing_annotations = False
```
I appreciate your the review.
=> Enhancement: ignore existing annotations

monkeytype/cli.py, tests/test_cli.py
This implements issue #58. [`difflib.ndiff`](https://docs.python.org/2/library/difflib.html#difflib.ndiff) is used. In the current implementation, only stubs that differ are shown to users. 
Demo:
```python
def func_anno(a: int, b: str) -> None:
pass
def func_anno2(a: str, b: str) -> None:
pass
```
Two traces: 
` CallTrace(func_anno, {'a': int, 'b': int}, int)` <- different from the existing annotation
` CallTrace(func_anno2, {'a': str, 'b': str}, None)`
Output:
```
- def func_anno(a: int, b: str) -> None: ...
?                          ^ -     ^^ ^
+ def func_anno(a: int, b: int) -> int: ...
?                          ^^      ^ ^
```
Demo 2:
```python
def func_anno(a: int, b: str) -> None:
pass
def super_long_function_with_long_params(
long_param1: str,
long_param2: str,
long_param3: …
```
=> Enhencement: stub --diff

monkeytype/cli.py, tests/test_cli.py
This PR makes the CLI error messages a little more explicit.
I was trying to mistakenly pass in file system paths for modules, which didn't work. :)
=> Improve CLI error messages

monkeytype/db/base.py, monkeytype/tracing.py, tests/db/test_base.py
This commit moves the filtering logic for __main__ modules to the CallTraceStoreLogger.  @carljm is this what you were thinking?
All of the current tests are passing locally for me and it is back to working order in IPython.  If this is in the right direction I'll start ticking off the contribution guidelines requirements.
=> The minimum changes to allow __main__ modules to be typed. #68

monkeytype/cli.py, tests/test_cli.py
Don't use shell mode when invoking retype. Previously, we weren't
escaping spaces in filenames when invoking retype. By passing an
argument list to `subprocess.run` we allow it to take care of
properly escaping arguments.
Fixes #77
=> Correctly handle spaces when applying stubs via retype

monkeytype/cli.py
When specifying a custom configuration (or using any other command line flag), `sys.argv` is not correct for the script being run:
test.py:
```python
import sys
print(sys.argv)
```
```
> monkeytype -c sample.monkeytype_config:CONFIG run test.py
['test.py', 'run', 'test.py']
```
This fix modifies `sys.argv` based on argument parsing, rather than a hard-coded value.
=> Fix issue with passing monkeytype cli flags to module

monkeytype/cli.py, tests/test_cli.py
Issue #90 
The error arises because `module_path` used in `complain_about_no_traces` is only added for `stub_parser` and `apply_parser` these two but not the `list_module_parser`.
See: 
https://github.com/Instagram/MonkeyType/blob/629d63d8abe6b0c07750e6dd17a71a809e196370/monkeytype/cli.py#L64-L69
https://github.com/Instagram/MonkeyType/blob/629d63d8abe6b0c07750e6dd17a71a809e196370/monkeytype/cli.py#L293-L302
https://github.com/Instagram/MonkeyType/blob/629d63d8abe6b0c07750e6dd17a71a809e196370/monkeytype/cli.py#L315-L324
=> Fix error when no module exist (#90)

.circleci/config.yml, Pipfile, Pipfile.lock, monkeytype/compat.py, monkeytype/encoding.py, monkeytype/stubs.py, monkeytype/typing.py, tox.ini
Fixes #78.
This isn't especially pretty, but it seems to work (i.e. passes all the tests on both Python 3.6 and 3.7). The changes are all due to extensive updates to the internals of the `typing` module in Python 3.7; unfortunately we have to make use of those internals.
Also includes the necessary changes to run tests etc under both Python 3.7 and 3.6 on CircleCI.
=> Python 3.7 support.

demo/test_inbox.py
Workaround for problem detected in https://github.com/Instagram/MonkeyType/issues/102
This will be necessary anyway to have a full appveyor build because demo tests are run as part of the regular tests (see the output of pytest -v)
=> Add workaround to Windows poor datetime accuracy to make tests succeed

CHANGES.rst, monkeytype/cli.py
Sometimes due to a failure decoding traces we have a partially-annotated function in stubs. There's no benefit in retype choking on that, just go ahead and apply what you know.
=> Pass --incremental to retype, partial annotation is OK.

monkeytype/stubs.py
This is not only unnecessary in stubs but also partially fixes #147 as existing annotations are no longer treated all as string literals.
[Depends on #145 and #146, ignore the first two commits]
=> Don't put stringified annotations in stubs

CHANGES.rst, monkeytype/encoding.py, monkeytype/typing.py, tests/test_encoding.py, tests/test_typing.py
It has now been documented (most recently in
https://bugs.python.org/issue37814) that the correct way to annotate an
empty tuple is `Tuple[()]`.
The runtime behavior of such an annotation is perhaps slightly
unexpected, in that `Tuple[()].__args__ == ((),)`, rather than `()` as
you might expect it would be (to parallel e.g. `Tuple[int, str].__args__
== (int, str)`).
On the other hand, this oddity is "useful" in that `Tuple.__args__ ==
()`, so this allows us to distinguish at runtime un-subscripted `Tuple`
(which I think must be interpreted as implicitly `Tuple[Any,...]` to
parallel e.g. `List` being equivalent to `List[Any]`?) from `Tuple[()]`.
This pull request makes MonkeyType's handling of tuple types consistent,
in that `Tuple` will round-trip to `Tuple` and `Tuple[()]` to …
=> Handle empty tuples consistently. Fixes #136.

CHANGES.rst, monkeytype/typing.py, tests/test_typing.py
This change will allow instance of collections.defaultdict to be typed as typing.DefaultDict, currently they are typed as collections.defaultdict. Type of Key and Value are determined similar to the way it is determined for Dict.
This is my first time creating a pull request. 
Please let me know if you have comments or would like me to make any changes.
=> Typing support for collections.defaultdict

CHANGES.rst, doc/configuration.rst, monkeytype/config.py
Generating new TypedDict subclasses in stubs breaks `--apply` because retype doesn't support moving these over to the code. Disable this feature by default (but leave it available via config for those who wish to enable it), at least for now until we can resolve that issue.
=> Disable TypedDict generation by default.

Pipfile, Pipfile.lock, monkeytype/stubs.py, monkeytype/util.py, tests/test_util.py
The `stringcase` package seems to use only `distutils`, but not
`setuptools`. This is causing problems when installing MonkeyType elsewhere.
Since we only need one function from the package, just roll it by hand.
=> Handroll pascal_case to remove dependency on `stringcase`.

monkeytype/stubs.py, tests/test_stubs.py
Fixes #74 and relates to #76 
In `render_parameter` additional logic is used to wrap `Optional` around a type annotation. This add a type annotation without importing `Optional` from `typing`, so if `Optional` has not been imported yet this will raise errors. This patch adds that logic in `get_imports_for_signature` to prevent this error. 
https://github.com/Instagram/MonkeyType/blob/47a77b01dea96c409b391cb5062582cb515ef571/monkeytype/stubs.py#L337
=> Import Optional if default param is None to match renderer

doc/tracing.rst
An example of `CallTracer` seems does not reflect newly added positional argument (missing `max_typed_dict_size`)
https://github.com/Instagram/MonkeyType/blob/56a688efccedd66521542144cd0afa4dc1e5e562/monkeytype/tracing.py#L190-L196
=> Fix an example of CallTracer

.flake8, Pipfile.lock, monkeytype/cli.py, setup.py, tests/test_cli.py, tests/test_stubs.py
It should be safe to remove the `args.existing_annotation_strategy = ExistingAnnotationStrategy.REPLICATE` line from `apply_stub_handler` because that is now the default value in `args`.
This needed the latest ApplyTypeAnnotationsVisitor from libcst.  Set the minimum libcst version to 0.3.5. (Another reason for this PR was that I unthinkingly changed a public function signature in a backward-incompatible way once again :(. Hope to keep that in mind next time.)
Note: I ran `pipenv update -d` to update the packages. This ended up upgrading pyflakes, which [now errors](https://github.com/PyCQA/pyflakes/pull/516) on `List[make_forward_ref('Foo')]` saying "undefined name 'Foo'", probably because it's a literal non-class string within a container. So, I've temporarily silenced these errors in …
=> Allow `apply` to overwrite existing annotations using CLI flag.

README.rst
The markup version of the readme that is displayed for the main page in this repo contains the following bad link:
"stub files"
Status code [404:NotFound] - Link: http://mypy.readthedocs.io/en/latest/basics.html#library-stubs-and-the-typeshed-repo
As per info here: https://github.com/python/mypy/issues/4851#issuecomment-399333461
This link has moved and is now: https://mypy.readthedocs.io/en/latest/getting_started.html#library-stubs-and-typeshed
**Extra**
This bad link was found by a tool I recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
Re-check this Repo using the tool’s website: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2fInstagram%2fMonkeyType
If this has been helpful, …
=> The README file in this repo has a bad link - [404:NotFound]  - "stub files"

demo/pytest.ini
@carljm I am working on issue #144 Switch to typing-inspect for as much type-inspection as possible and came across this problem. 
- I was following the readme in dir /demo/readme.md
```
The file inbox.py in this directory has some code implementing aggregation of
notifications in a hypothetical inbox system.
The code looks like it's in pretty good shape; it has thorough tests (in
test_inbox.py`) that cover every possible code path. You can run the tests with
pytest and see them pass. But there are a few latent bugs hiding in there!```
- Running pytest following along with the readme resulted in the following: 
```
demo % pipenv run pytest
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov --cov-report=term-missing …
```
=> coverage plugin update

RELEASING.rst, doc/conf.py, monkeytype/__init__.py, setup.cfg
Since the `attr:` feature of `setup.cfg` actually imports the module,
using it requires that all transitive dependencies of
`monkeytype/__init__.py` be importable, just in order to parse metadata.
This is unnecessary.
=> Move canonical version directly into setup.cfg.

monkeytype/compat.py
I got `AttributesError` for `IO` like below.
```
File "/tmp/tmpvenv.CeMKc5V/lib/python3.8/site-packages/monkeytype/compat.py", line 40, in qualname_of_generic
return typ._name or typ.__origin__._name or typ.__origin__.__qualname__
AttributeError: type object 'IO' has no attribute '_name'
```
It seems to me like `monkeytype.compat.qualname_of_generic` is intended to work even if `typ` doesn't have `_name`.
Why don't you use `getattr`?
=> Use getattr with None to avoid AttributesError

setup.cfg
LibCST has seen a bunch of important fixes to apply type annotation and others that affect MonkeyType. For example https://github.com/Instagram/LibCST/issues/690 should be fixed now.
Note to reviewers: LibCST 0.4.0 and onwards comes with binary wheels, whereas before it was a pure python package.
=> Bump required libcst version

monkeytype/typing.py
There is a small typo in monkeytype/typing.py.
Should read `heterogeneous` rather than `heterogenous`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, heterogenous -> heterogeneous

CONTRIBUTING.rst, doc/faq.rst
- Branch name is now `main` not `master`
- Add FAQ how to reenable generation of `TypedDict`s
=> Add TypedDict FAQ, fix branch name in CONTRIBUTING

monkeytype/tracing.py, tests/test_tracing.py
Fixes #305 by adding logic to `tracing.get_func` that goes up the stack trace and looks for the function in the locals.
Added a test for this, and also for locally defined class tracing which was already supported.
=> Add support for tracing locally defined functions

CHANGES.rst, doc/generation.rst, monkeytype/typing.py, tests/test_typing.py
This is an attempted fix for #298: It replaces a union of types by the most common (i.e., most specific) base of all types in the union.
=> Add "most common base" rewriter

.github/workflows/test.yml
acording to https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/ (and our failing test) v3 is not longer supported... upgrading to v4
=> upgrade upload artifact to v4
